I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1052, in script
    show Quol angry at center_lower with Dissolve(0.3)
Exception: Image 'Quol' does not accept attributes 'angry'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1052, in script
    show Quol angry at center_lower with Dissolve(0.3)
  File "C:\Users\100ga\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\100ga\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "C:\Users\100ga\Downloads\renpy-8.1.3-sdk\renpy\exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\100ga\Downloads\renpy-8.1.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\100ga\Downloads\renpy-8.1.3-sdk\renpy\display\transform.py", line 1043, in _duplicate
    args.extraneous()
  File "C:\Users\100ga\Downloads\renpy-8.1.3-sdk\renpy\display\core.py", line 362, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'Quol' does not accept attributes 'angry'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Concert of Liberation DEMO 1.0
Wed Dec 13 23:03:09 2023
