I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 199, in script
    show Lenorra at Transform (yalign=0.1, xaligh=0.5) with Dissolve(0.5)
  File "game/script.rpy", line 199, in <module>
    show Lenorra at Transform (yalign=0.1, xaligh=0.5) with Dissolve(0.5)
Exception: Unknown transform property: 'xaligh'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 199, in script
    show Lenorra at Transform (yalign=0.1, xaligh=0.5) with Dissolve(0.5)
  File "C:\Users\100ga\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\100ga\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1387, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\100ga\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1387, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\100ga\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\100ga\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 199, in <module>
    show Lenorra at Transform (yalign=0.1, xaligh=0.5) with Dissolve(0.5)
  File "C:\Users\100ga\Downloads\renpy-8.1.3-sdk\renpy\display\transform.py", line 617, in __init__
    raise Exception("Unknown transform property: %r" % k)
Exception: Unknown transform property: 'xaligh'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Concert of Liberation 1.0
Sun Dec 10 23:59:39 2023
